<?xml version='1.0' encoding='UTF-8'?>
<userScreen>
  <screenName>TXTCOMBO</screenName>
  <screenType>W</screenType>
  <templateScreen>Y</templateScreen>
  <formType>F</formType>
  <langID>en-us</langID>
  <screenFormat>U</screenFormat>
  <screenDesc>Text + Combo</screenDesc>
  <screenData>
    <screenDesc>Text + Combo</screenDesc>
    <screenFormat>U</screenFormat>
    <version>0</version>
    <screenDefinition definitionVersion="2">
      <title>Text + Combo</title>
      <newForm>awdForm</newForm>
      <class>dstTheme</class>
      <screenURL></screenURL>
      <includeList/>
      <linkList/>
      <customRules></customRules>
      <customProperties></customProperties>
      <page index="0">
        <title>Text + Combo</title>
        <width>740</width>
        <height>265</height>
        <transformVariables></transformVariables>
        <dataDictionary>
          <fieldType>textInput</fieldType>
          <id>MEMO_0</id>
          <name>MEMO</name>
          <sequence></sequence>
          <label>Memo</label>
          <class></class>
          <dataDictionary>MEMO</dataDictionary>
          <externalDataDictionary></externalDataDictionary>
          <default></default>
          <fieldFormat>Alphabetic</fieldFormat>
          <decimals>0</decimals>
          <length>60</length>
          <mask></mask>
          <maskOverride>N</maskOverride>
          <helpText></helpText>
          <tabIndex>0</tabIndex>
          <required>N</required>
          <readOnly>N</readOnly>
          <password>N</password>
          <allowSmartControl>Y</allowSmartControl>
          <labelPosition></labelPosition>
          <top>20</top>
          <left>20</left>
          <width>200</width>
        </dataDictionary>
        <dataDictionary>
          <fieldType>select</fieldType>
          <id>STAT_1</id>
          <name>STAT</name>
          <sequence></sequence>
          <label>Status</label>
          <class></class>
          <dataDictionary>STAT</dataDictionary>
          <externalDataDictionary></externalDataDictionary>
          <options>
            <row>
              <listValue>A</listValue>
              <listName>Active</listName>
            </row>
            <row>
              <listValue>I</listValue>
              <listName>Inactive</listName>
            </row>
          </options>
          <rootName></rootName>
          <helpText></helpText>
          <tabIndex>1</tabIndex>
          <required>N</required>
          <routingList>N</routingList>
          <buttonLabel>Label</buttonLabel>
          <labelPosition></labelPosition>
          <top>90</top>
          <left>20</left>
          <width>200</width>
        </dataDictionary>
        <dataDictionary>
          <fieldType>select</fieldType>
          <id>DCMB_2</id>
          <name>DCMB</name>
          <sequence></sequence>
          <label>Distro</label>
          <class></class>
          <dataDictionary>DCMB</dataDictionary>
          <externalDataDictionary></externalDataDictionary>
          <options>
            <row>
              <listValue>X1</listValue>
              <listName>First</listName>
            </row>
            <row>
              <listValue>X2</listValue>
              <listName>Second</listName>
            </row>
            <row>
              <listValue>X3</listValue>
              <listName>Third</listName>
            </row>
          </options>
          <rootName></rootName>
          <helpText></helpText>
          <tabIndex>2</tabIndex>
          <required>N</required>
          <routingList>N</routingList>
          <buttonLabel>Label</buttonLabel>
          <labelPosition></labelPosition>
          <top>160</top>
          <left>20</left>
          <width>200</width>
        </dataDictionary>
      </page>
    </screenDefinition>
  </screenData>
  <publicLink>N</publicLink>
</userScreen>
